packages:
  - packages/*
  - '!packages/components'
  - packages/components/*
  - '!packages/workflows'
  - packages/workflows/*
  - '!packages/types'
  - packages/types/*

onlyBuiltDependencies:
  - esbuild
  - nx
  - puppeteer
