packages:
  - packages/*
  - '!packages/components'
  - packages/components/*
  - '!packages/oauth2-cli'
  - packages/oauth2-cli/*
  - '!packages/types'
  - packages/types/*
  - '!packages/workflows'
  - packages/workflows/*

onlyBuiltDependencies:
  - esbuild
  - nx
  - puppeteer
