import { DateString, NumericBoolean } from '@battis/descriptive-types';

export type Category = {
  group_id: number;
  categoryDescriptionsEnabled: boolean;
  imageMax: number;
  imageTitlesEnabled: boolean;
  imageCaptionsEnabled: boolean;
  imageDescriptionsEnabled: boolean;
  standardWidth: number;
  standardHeight: number;
  zoomWidth: number;
  zoomHeight: number;
  thumbWidth: number;
  thumbHeight: number;
  thumbEnabled: boolean;
  zoomEnabled: boolean;
  AssociationId: number;
  ContentId: number;
  MpSelected: boolean;
  MaxPageNum: number;
  TotalRows: number;
  PublicGroupInd: boolean;
  isPublic: NumericBoolean;
  ContextLabelId: number;
  ContextValue: number;
  PrimaryInd: number;
  GroupName: string;
  Id: string;
  Name: string;
  ExpireDate: DateString | null;
  PublishDate: DateString | null;
  Primary: boolean;
  ContextLabel: number;
  albumId: number;
  IsPublicCategory: NumericBoolean;
};
