export type ContentItem = {
  AlbumDescription?: string | null;
  AllowDownload?: NumericBoolean | null;
  AllowDownloadMsag?: string | null;
  CellIndex: number;
  ColumnIndex: number;
  ContentId: number;
  ContentIndexId: number;
  ContentItemId: number;
  CoverFileId?: number | null;
  ExpireDate?: DateString | null;
  FileEdited?: string | null;
  FileName?: string | null;
  FilenameUrl?: string;
  FilePath?: string | null;
  FilesInProcessing: number;
  FilesProcessed: number;
  FriendlyFileName?: string | null;
  GenericSettings?: any | null; // FIXME type
  HasCorruptedFile?: number | null;
  Headline?: string | null;
  HoverFileName?: string | null;
  HoverImageOriginalFilename?: string | null;
  IsPhotoProcessed?: number | null;
  LinkImage?: string | null;
  LinkImageId?: number | null;
  Locked: boolean;
  LongDescription?: string | null;
  OriginalFilename?: string | null;
  PhotoCorrupted?: number | null;
  PresentationHeight?: number | null;
  PresentationTarget?: string | null;
  PresentationWidth?: number | null;
  PublishDate?: DateString | null;
  PublishedIndicator: number;
  RenditionsComplete: number;
  RowIndex: number;
  Shared: number;
  ShortDescription: string;
  SortOrder: number;
  SubCategory?: string | null;
  TotalFiles: number;
  Url?: string | null;
};
